Fix CMake build with SASL enabled
When building librdkafka with SASL enabled (which happens by default if you have libsasl2 installed), the compilation fails because the macros
WITH_SASL_SCRAM and WITH_SASL_CYRUS are never defined and things in the code depend on them:

```
[ 34%] Building C object src/CMakeFiles/rdkafka.dir/rdkafka_sasl_cyrus.c.o
/home/lukas/work/librdkafka/src/rdkafka_sasl_cyrus.c: In function ‘rd_kafka_sasl_cyrus_broker_term’:
/home/lukas/work/librdkafka/src/rdkafka_sasl_cyrus.c:528:49: error: ‘rd_kafka_broker_t {aka struct rd_kafka_broker_s}’ has no member named ‘rkb_sasl_kinit_refresh_tmr’
         rd_kafka_timer_stop(&rk->rk_timers, &rkb->rkb_sasl_kinit_refresh_tmr,1);
                                                 ^
/home/lukas/work/librdkafka/src/rdkafka_sasl_cyrus.c: In function ‘rd_kafka_sasl_cyrus_broker_init’:
/home/lukas/work/librdkafka/src/rdkafka_sasl_cyrus.c:543:50: error: ‘rd_kafka_broker_t {aka struct rd_kafka_broker_s}’ has no member named ‘rkb_sasl_kinit_refresh_tmr’
         rd_kafka_timer_start(&rk->rk_timers, &rkb->rkb_sasl_kinit_refresh_tmr,
                                                  ^
src/CMakeFiles/rdkafka.dir/build.make:1214: recipe for target 'src/CMakeFiles/rdkafka.dir/rdkafka_sasl_cyrus.c.o' failed
```

After setting the macros in config.h from CMake, the build completes without problems.